name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
  TRELLO_OAUTH_TOKEN: ${{ secrets.TRELLO_OAUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies and test
        run: |
          npm ci
          npx sst test
